### PR TITLE
Experiment with "lookahead" functionality

### PR DESCRIPTION
**Pull request by sidtalia**
Basic outline :
in trajtrack.cc, in function GetTarget : 
1) Find the nearest point where the curvature is maximum ( a local "maxima" for curvature, although it is indifferent to the direction of turning. The local maxima is found by evaluating the product of derivatives of curvature around a point. if the product of current derivative and previous derivative is negative, the sharpest point was just encountered. The product is positive as long as the curvature's magnitude keeps increasing)
2) Find the distance to that point (for now using euclidean distance. Can be improved later). 

in controller.cc, in function GetControl, in the if condition for autodrive : 
3) Evaluate whether braking is required by evaluating the deceleration required to hit the maximum speed at the point of maximum kappa found in 1). the deceleration is computed as dv/dx*current velocity (dv/dx * dx/dt = dv/dt . This works as long as we assume the deceleration to be uniform. again, these assumptions can be improved, but the basic idea would remain). 
If the deceleration required is more than half the traction limit (because some traction will be required for turning too. Again, an assumption), then set the target velocity as the velocity at that point (max kappa point) and if not then set the target velocity as the velocity for the current kappa or the config.speed limit (whichever is smaller).

### CODE REVIEW

**Review by siedentop — COMMENTED** [review]
Please fix the syntax. The equal sign is necessary, AFAIK. You can find out more about this clang-tidy check here: https://clang.llvm.org/extra/clang-tidy/checks/bugprone-argument-comment.html

**Comment by siedentop** [comment]
Nice idea. Another idea would be to annotate the offline computed path with target velocities for each point. Offline it’s easier to get the optimal speed based on friction circle and curvature for each point. Then, this somewhat heuristic-y approach in this pull request wouldn’t be necessary. 

Another question based off the description of the PR, not the code: if the ideal velocity is dependent on being able to break for the slowest corner what happens in this scenario. For simplicity imagine a straight track (not closed loop) with two corners. The first corner has curvature just below the second corner’s curvature. Then the car will be way too fast for the first corner. I hope I explained that well.

**Comment by siedentop** [comment]
Update regarding my earlier comment: from the code I can see that you find the first local curvature maximum. This is better than my assumption however it remains that the speed might be too high on the second maximum.

**Comment by naughtyStark** [comment]
Hi! Thank you for your time!
I will address the second question first.
I can imagine a certain case where this method will likely not work great. I am imagining a turn like turn 15 on circuit of americas 
image

However, the catch here is that the path is optimized before-hand (this is something that 
happens already) and the optimized path around turns like turn 15 on CoAs would actually only have 1 local maxima and not 2. I am not sure exactly how the path is being optimized here, but if 2 local maximas are in succession (in a track), the optimized path only contains 1 local maxima (speaking from my experience as a racer, not a programmer or mathematician ).
image
(you could go in either direction, if approaching turn 15, there is actually only 1 maxima. If approaching turn 13 from turn 15, there is still only 1 maxima even though there are 2 turns).

So the problem that you describe is not very likely to occur. Nonetheless. I will think about it and fix it ASAP.

Answering the first question :
I can see the validity and benefit of the offline approach, the assumptions can be avoided because computational expense isn't a big deal (not that it's a big deal right now either). One correction I would like to make to your comment is that you wouldn't need the velocity at each point (since we can already find that using kappa), you'll need the deceleration/acceleration at each point (which will be computed in a way similar to the approach outlined in this PR ). That would allow us to make the most of the friction available to the car at all times (which is how human racers find the ideal braking points and the racing line in general, by keeping the car at the limit all the time). This approach works great for time attacks on a track where the conditions never change (so basically almost like a basic video game).

However, the offline approach, in my opinion, is not a good one (and in my car, as rudimentary as it is, I use an online method for generating trajectory (Its not exactly generating a trajectory but I will avoid going into the details here) ) because the system loses flexibility and becomes very rigid in how it operates. The reason why "rigidity" is bad is because the next logical step in autonomous racing is to race against other cars without being oblivious to them, which will require re-planning the path in real time (this is kind of why in local races or online racing sessions you see a lot of guys do really good lap-times in the qualification runs but they get lost in the back of the pack in the actual race, because they aren't used to re-planning their path while they are racing). If path re-planning (or maybe just diverting from the ideal path for a very small amount of time) in real time is required, then a method to find the optimal braking point in real time is also required because your speed coming out of the overtaking/dodge/defense maneuver will be different from your pre-calculated optimal speed.

The method can certainly be improved. I was just trying to find a quick and dirty fix so that I could create a pull request and bring this idea to light. We can develop this method further and make it less "heuristic-y". 

As for the review, my bad, I was not aware of the importance of the "equal to" sign. I will make the correction ASAP. 

P.S. In case you want to see my self driving car project (very rudimentary compared to this) : https://github.com/naughtyStark/Self-driving-car

Thanks,
Regards,
Sidharth.

**Comment by naughtyStark** [comment]
> Update regarding my earlier comment: from the code I can see that you find the first local curvature maximum. This is better than my assumption however it remains that the speed might be too high on the second maximum.

I came up with a solution for this. For now it only considers 2 local maximas of kappa ahead of the current position. However it can be made to consider multiple maximas following a similar logic (if there is a need for such a feature, I will implement that too, however, having 3 local maximas so close together and so drastically different in magnitude that you have to consider the 3rd maxima is just bad optimization in my opinion and somewhat unrealistic from my experience). 

An intuitive explanation of how it works : 
1) find the first 2 local maximas  ahead of the car.
2) find the gap (distance between them) and store their kappa values.
3) put values into a mathematical condition to check if the second maxima is such that brakes must be applied according to the second maxima and not the first (basically if the distance between the 2 points is not very large but the velocity difference is, then premature braking must be done in accordance to the second maxima.) 

Mathematical explanation for the final condition : 

proof_1

proof_2
The 2 curvatures are just 2 examples of the possible cases where this might become useful.

proof_3
you can ignore the relu part.

proof_4

The k's here are magnitudes of k's so the negative values don't matter.

**Comment by a1k0n** [comment]
I'm sorry I haven't had time to fully digest your method here... however, a simpler approach which is less dumb than the existing lookahead but still works would be to just compute the maximum velocity at every point on the track, and then iterate backwards in a loop setting maxv_i = min(maxv_i, maxv_{i+1} - brake_accel*dt), where dt is computed from the distance between successive points (a fixed quantity) and the average velocity (maxv_i + maxv_{i+1})/2, and find the fixed point of that whole thing after a couple iterations. You're right, it should also figure it has less braking acceleration when there is also a lateral acceleration. But there's no arbitrary limit of looking at two maxima, just a linear ramp-down to each local maxima.

**Comment by naughtyStark** [comment]
Hi! Thank you for taking some time for reviewing the PR.

I apologize, I am not sure if I understand the method you have stated. As far as I can tell it appears like a method that finds the first local maxima ahead of the car but I've only gathered that from the last line of your comment. It also appears to be a recursive method as far as I can tell but that is as much as I could understand of the method. Could you please explain it a little more?

Thanks, 
Regards, 
Sidharth.

**Comment by a1k0n** [comment]
The assumption is that we have a precomputed path around the track (either from an online optimization strategy or computed offline), and we can compute the maximum velocity from the curvature at each point; I believe that was your starting point, too.

To make the trajectory feasible, we need to lower the maximum velocity at each point to account for a certain amount of braking deceleration ahead of each turn.

So my idea is, loop for each point on the track, in reverse order, and, if necessary, lower the precomputed maximum speed to the value required for braking to slow the car to the maximum velocity at the next point while staying within braking acceleration limits.

At least two iterations through the loop are necessary just to handle the boundary condition between the first/last point you iterate through, and more may be necessary because of the adjustments to the estimated speed through each point would affect the time taken between points (but only a little).

**Comment by naughtyStark** [comment]
Hi! Thanks for taking to explain the concept! I appreciate it.

The first 2 paragraphs : True and yes.

>So my idea is, loop for each point on the track, in reverse order, and, if necessary, lower the precomputed maximum speed to the value required for braking to slow the car to the maximum velocity at the next point while staying within braking acceleration limits.

>At least two iterations through the loop are necessary just to handle the boundary condition between the first/last point you iterate through, and more may be necessary because of the adjustments to the estimated speed through each point would affect the time taken between points (but only a little).

While this will most likely work (I'll see if I can mathematically prove that this method converges/ find if there is some kind of guarantee in this method although I am not very good at math so I wouldn't bet on myself being able to do it but I'll try none the less) it seems to bear a computational cost higher than the method I suggested. 

In my method, we simply find the first and second maxima closest to the car's position( and the process for finding them stops when the end of the loop has been reached. The process of finding a maxima is fairly simple too, fits in a single line of code and requires no extra iterations), see if the deceleration between the  first and the second maxima is large enough to consider the second maxima more important and run a simple check in the controller.cc to see if braking is needed or not to hit the target speed at whichever maxima that was deemed important. 

You could question whether or not this method guarantees that we don't miss a point where the required deceleration is higher than the available deceleration. The aforementioned point, if it exists, will occur in the locality of the maxima and therefore finding the maxima guarantees that you won't miss points where the required deceleration is more than the available deceleration.

Thanks,
Regards,
Sidharth.

**Comment by naughtyStark** [comment]
This project has come a long way since back then! Good to see that you're in the 10 m/s range now (albeit with foam tires)! Would you mind if I take a look at the trackplan method you use? I want to use something similar in my own project as well: https://github.com/naughtyStark/Self-driving-car-STM-32 .
Also, since you have incorporated a lookahead function in your own way, this pull request seems irrelevant so you can close the pull request.

**Comment by a1k0n** [comment]
Yes, I've come up with a better way to generate optimal racing policies. It's all committed in this repo; my latest code is actually using value iteration in PyCUDA to generate a lookup table -- see `tools/trackplan/vicuda.py`. I just pushed the data for the track I'm racing on so it should run out of the box. there's also valueiter.py for the CPU version but it's so much slower I abandoned it and it's no longer compatible.

**Pull request closed without merging**
